name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm" # Optional but recommended for caching pnpm dependencies
          corepack: true # Explicitly enable Corepack

      - name: Enable Corepack for pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        # --with-deps might behave slightly differently or have different requirements
        # across OSes. Playwright generally handles this well, but be aware.
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report/
          retention-days: 30
